AWSTemplateFormatVersion: 2010-09-09
Description: >-
  vc-api
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  getAllCompaniesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/api/lambda.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      MemorySize: 512
      Timeout: 100
      Description: A simple get api end point hosted with Lambda + API Gateway integration using Fastify
      Events:
        Api:
          Type: Api
          Properties:
            Path: /companies
            Method: GET
  postForwardingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/api/lambda.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 100
      Description: A simple get api end point hosted with Lambda + API Gateway integration using Fastify
      Events:
        Api:
          Type: Api
          Properties:
            Path: /forwarding
            Method: POST

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
